### ISSUE TITLE
ACCESS driver error when runtype set

### ISSUE THREAD

**Issue by aidanheerdegen** [marshallward/payu#104]
Fabio had this error thrown when he was copied an existing model config but wanted to start from initial conditions:

```python
[fbd581@raijin2 1deg_jra55v13_ryf8485_test]$ payu setup
Traceback (most recent call last):
  File "/apps/payu/0.8.1/bin/payu", line 8, in <module>
    cli.parse()
  File "/apps/payu/0.8.1/lib/payu/cli.py", line 61, in parse
    run_cmd(**args)
  File "/apps/payu/0.8.1/lib/payu/subcommands/setup_cmd.py", line 18, in runcmd
    expt.setup(force_archive=force_archive)
  File "/apps/payu/0.8.1/lib/payu/experiment.py", line 348, in setup
    model.setup()
  File "/apps/payu/0.8.1/lib/payu/models/cice.py", line 171, in setup
    self.link_restart(setup_nml['pointer_file'])
  File "/apps/payu/0.8.1/lib/payu/models/cice.py", line 258, in link_restart
    assert input_path
AssertionError
```
This was solved by changing the following settings in his `ice/cice_in.nml`:
```fortran
runtype = 'continue'
restart = .true.
```
to
```fortran
runtype = 'initial'
restart = .false.
```
The `cice` driver sort of assumes these variables are set to `initial` and `.false.` and changes them to `continue` and `.true.` if it finds a restart directory, here:

https://github.com/marshallward/payu/blob/master/payu/models/cice.py?#L145

So it should probably set them to `initial` and `.false.` if there is no restart dir.

Have I missed another case where this would be harmful?

**Comment by marshallward** [comment]
I think you know as much as me or anyone else on this.  But it sounds like a good idea.

**Comment by aidanheerdegen** [comment]
I said it was an access driver error, but I guess it is cice ...

**Comment by aidanheerdegen** [comment]
You're right. I'll amend my suggestion to say payu should catch this situation and tell the user that they have specified restart but there are no restarts found. Tell the user how to remedy the situation and then exit.

**Comment by aekiss** [comment]
Yes that sounds better to me

**Comment by marshallward** [comment]
I think I agree with you guys, since mistaken restart config is a big problem that could waste a lot of hours.

I wonder how this is handled in general though, how much are we cleaning up misconfigured jobs on submission?  My guess is a fair bit more than we might realise.

I wonder if its worth setting a policy around this and keeping things consistent.

**Comment by aidanheerdegen** [comment]
Different models do different amounts of fiddling with this. I'm not sure the policy could be much more than "make sure input is consistent with what we think it should be".

I'd probably be in favour of a bit more verbosity in payu in general, as this helps users to confirm what it is doing, and provides a bit of in-code documentation as well.

**Comment by aidanheerdegen** [comment]
Triaged, and decided that issuing a warning to the user is still a good idea and warranted.
