### ISSUE TITLE
postscript 

### ISSUE THREAD

**Issue by aidanheerdegen** [marshallward/payu#145]
When using `payu/0.11.2` postscript fails to launch due to `qsub` missing from PATH

```
$ cat mom-sis-01_c.e3818506
Traceback (most recent call last):
  File "/apps/payu/0.11.2/bin/payu-collate", line 11, in <module>
    load_entry_point('payu==0.11.2', 'console_scripts', 'payu-collate')()
  File "/apps/payu/0.11.2/lib/python3.6/site-packages/payu-0.11.2-py3.6.egg/payu/subcommands/collate_cmd.py", line 110, in runscript
    expt.postprocess()
  File "/apps/payu/0.11.2/lib/python3.6/site-packages/payu-0.11.2-py3.6.egg/payu/experiment.py", line 704, in postprocess
    rc = sp.call(cmd)
  File "/apps/python3/3.6.2/lib/python3.6/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/apps/python3/3.6.2/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/apps/python3/3.6.2/lib/python3.6/subprocess.py", line 1333, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'qsub'
$ which payu
/apps/payu/0.11.2/bin/payu
```

```
$ cat config.yaml 
# PBS flags
queue: express
project: v45
walltime: 1:00:00
ncpus: 120
mem: 226GB
jobname: mom-sis-01
qsub_flags: -W group_list=v45
runspersub: 5

# #collate_walltime: 10:00:00
#collate_mem: 16GB
collate:
    walltime: 4:00:00
    mem: 30GB
    ncpus: 1
    queue: express
    flags: -n4 -z -m
    exe: mppnccombine

archive: true

# exe_prefix: /short/public/aph502/env-wrapper.sh  

# Model config
model: mom
shortpath: /short/v45
exe: fms_MOM_SIS.tweaklangmuir
input: 
       - mom10/mosaic
       - mom10/common
       - /g/data/v45/mom/cnyf2
       - /g/data1/ua8/MOM/runoff/JRA55-do/v1-1/mom10/RYF9091
       # - mom10/mask_120/

# Misc
stacksize: unlimited

runlog: true

# runlog:
#    username: aidanheerdegen

postscript: ls.sh
$ cat ls.sh 
#!/bin/bash
#PBS -q copyq
#PBS -l ncpus=1
#PBS -l wd
#PBS -l walltime=1:00:00,mem=2GB
#PBS -P v45
#PBS -N test_post

ls
```

**Comment by marshallward** [comment]
`module('load', 'pbs')` should fix, though part of me wonders if `postscript` is worth continuing supporting.

I guess people do need it?

**Comment by aidanheerdegen** [comment]
It is currently the way all the synching to `/g/data3` is done. So yes it is required.

**Comment by aidanheerdegen** [comment]
I don't really understand why it was still working at all, but it seemed to be for some folks.

**Comment by marshallward** [comment]
most likely if they have `module load pbs` in their `.bashrc` etc then it will work

**Comment by aidanheerdegen** [comment]
Yeah, I wondered if that might be the case.

**Comment by aidanheerdegen** [comment]
Fixed in https://github.com/marshallward/payu/commit/7da634545b05e5804d8ccb629d9e0e29d2e9406c
