### ISSUE TITLE
Error with mitgcm executable compiled without netcdf (mnc) support

### ISSUE THREAD

**Issue by aidanheerdegen** [marshallward/payu#48]
Got this error when using an executable compiled without mnc support:

```python
Traceback (most recent call last):
  File "/jobfs/local/pbs/mom_priv/jobs/2567927.r-man2.SC", line 9, in <module>
    run_cmd.runscript()
  File "/apps/payu/0.5.1/lib/payu/subcommands/run_cmd.py", line 112, in runscript
    expt.setup()
  File "/apps/payu/0.5.1/lib/payu/experiment.py", line 345, in setup
    model.setup()
  File "/apps/payu/0.5.1/lib/payu/models/mitgcm.py", line 122, in setup
    f90nml.write(data_mnc_nml, data_mnc_path)
  File "/apps/payu/0.5.1/lib/f90nml/__init__.py", line 65, in write
    nml.write(nml_path, force=force)
AttributeError: 'dict' object has no attribute 'write'
```

Has f90nml changed so it doesn't support writing a vanilla dictionary? Does the dict have to be initialised as an f90nml object first?

**Comment by marshallward** [comment]
Yeah, confirmed.  This is using the older interface (that I thought was still working).
I will fix this in f90nml and close this issue once it's working (and installed on Raijin)

**Comment by marshallward** [comment]
Fixed in f90nml, Raijin install has been updated.
