### ISSUE TITLE
push fails when no organisation specified

### ISSUE THREAD

**Issue by aidanheerdegen** [marshallward/payu#78]
There is no default for GitHub organization, which leads to this error if none is specified:

```
  Traceback (most recent call last):
  File "/apps/payu/0.8a/bin/payu", line 8, in <module>
    cli.parse()
  File "/apps/payu/0.8a/lib/payu/cli.py", line 61, in parse
    run_cmd(**args)
  File "/apps/payu/0.8a/lib/payu/subcommands/push_cmd.py", line 20, in runcmd
    runlog.push()
  File "/apps/payu/0.8a/lib/payu/runlog.py", line 99, in push
    org_url = 'https://github.com/' + github_org
TypeError: cannot concatenate 'str' and 'NoneType' objects
```

I suggest checking for this and not attempting push and warning user.

**Comment by aidanheerdegen** [comment]
GitHub username is not a valid organization. Get this error when I tried it:
```
payu push                                                                                                                       
Traceback (most recent call last):
  File "/apps/payu/0.8a/bin/payu", line 8, in <module>
    cli.parse()
  File "/apps/payu/0.8a/lib/payu/cli.py", line 61, in parse
    run_cmd(**args)
  File "/apps/payu/0.8a/lib/payu/subcommands/push_cmd.py", line 20, in runcmd
    runlog.push()
  File "/apps/payu/0.8a/lib/payu/runlog.py", line 116, in push
    if not any(r['name'] == github_expt_name for r in resp.json()):
  File "/apps/payu/0.8a/lib/payu/runlog.py", line 116, in <genexpr>
    if not any(r['name'] == github_expt_name for r in resp.json()):```

I know this wasn't the intention, but it was the first thing I thought of to push to my user. The API requires a URL like so:

```wget https://api.github.com/users/aidanheerdegen/repos```

I'm not making a separate issue for this to be supported, as I think they're linked. I'm thinking the username should be the default "organization" if none is specified, so grabbing the repos will have to support organizations as well as users (try/except?).

**Comment by marshallward** [comment]
I don't think its any problem to support both users and organizations.  Personally I don't want all these configs in my personal account, but it's easy enough to support.

Probably a lot of ways to go on this, so maybe I will come by for a chat.

**Comment by marshallward** [comment]
New version only looks in user repos for existing deploy keys

**Comment by marshallward** [comment]
This may be fixed in the latest push.

**Comment by marshallward** [comment]
`payu ghsetup` defaults to ones private account, so closing this issue.
