### ISSUE TITLE
Pull request #88 broke old runs

### ISSUE THREAD

**Issue by aidanheerdegen** [marshallward/payu#91]
Pull request https://github.com/marshallward/payu/pull/88 broke old runs which did not have the config files copied into output.

```
Traceback (most recent call last):
  File "/jobfs/local/pbs/mom_priv/jobs/1396319.r-man2.SC", line 9, in <module>
    run_cmd.runscript()
  File "/projects/v45/apps/payu/test/lib/payu/subcommands/run_cmd.py", line 122, in runscript
    expt.setup()
  File "/projects/v45/apps/payu/test/lib/payu/experiment.py", line 345, in setup
    model.setup()
  File "/projects/v45/apps/payu/test/lib/payu/models/cice.py", line 151, in setup
    prior_setup_nml = f90nml.read(prior_nml_path)['setup_nml']
  File "/projects/v45/python/f90nml/__init__.py", line 19, in read
    return Parser(verbose).read(nml_fname)
  File "/projects/v45/python/f90nml/parser.py", line 41, in read
    nml_file = open(nml_fname, 'r')
IOError: [Errno 2] No such file or directory: '/short/v45/amh157/access-om2/archive/1deg_jra55_ryf8
485/restart250/ice/cice_in.nml'
```

**Comment by aidanheerdegen** [comment]
Fixed in this PR https://github.com/marshallward/payu/pull/89
