### ISSUE TITLE
Error when job name is a number

### ISSUE THREAD

**Issue by aidanheerdegen** [marshallward/payu#95]
When jobname is a number, e.g.
```yaml
jobname: 12345
```
Get the following error with `payu setup` followed by `payu sweep`
```python
Traceback (most recent call last):
  File "/apps/payu/0.8/bin/payu", line 8, in <module>
    cli.parse()
  File "/apps/payu/0.8/lib/payu/cli.py", line 61, in parse
    run_cmd(**args)
  File "/apps/payu/0.8/lib/payu/subcommands/sweep_cmd.py", line 18, in runcmd
    expt.sweep(hard_sweep)
  File "/apps/payu/0.8/lib/payu/experiment.py", line 807, in sweep
    short_job_name = self.config.get('jobname', default_job_name)[:15]
TypeError: 'int' object has no attribute '__getitem__'
```

Here:

https://github.com/marshallward/payu/blob/master/payu/experiment.py#L807

The  short_job_name variable should be converted to string before attempting the slice operation

**Comment by marshallward** [comment]
hah, nice one!  Just pushed a fix: 3d453ae

**Comment by aidanheerdegen** [comment]
10 minute turn around. Impressive.

**Comment by aidanheerdegen** [comment]
I have tested and confirmed it fixes the bug.
