### ISSUE TITLE
ncpus can exceed total CPU count in a coupled model

### ISSUE THREAD

**Issue by marshallward** [marshallward/payu#97]
It is currently possible to request more CPUs than used by the submodels.  In the words of Khadgar,

> Fewer would be inadequate.  More would be absurd.

Since payu already pads requests by the minimum amount, this is at best unnecessary and at worst wasteful.  It's also potentially confusing for those of us trying to analyse these big jobs!

This was noticed in ACCESS-OM2 where 5559 cpus were used but 5600 were requested.

> Don't question my methods!

**Comment by aekiss** [comment]
These were the notes I took at the time we decided on `ncpus: 5600`. It was done to make it more convenient to switch between normal and normalbw, though it does seem slightly wasteful so maybe we should scale it back.

* ncpus must be a multiple of nodesize (28), and at least the sum of the submodel cpus, in our case a total of 1+4358+1200=5559 cpus.
    * `5559/28=198.5` so need at least ncpus=`199*28=5572` on normalbw
    * `5559/16=347.4` so need at least ncpus=`348*16=5568` on normal (which is what Nic had set)
* but there's also a **sweet spot**: `ncpus=5600=200*28=350*16` so will work with both normal and normalbw (*but still need to adjust nodesize!*)
    * This is a waste of only 
        * 28cpus=0.50% on normalbw (1 node)
        * 32cpus=0.57% on normal (2 nodes)

**Comment by aidanheerdegen** [comment]
I think what Marshall is getting at is that it is not necessary (and may be considered harmful) to specify `ncpus` for individual submodes and then again for the simulation as a whole. `payu` will just add up the `ncpus` for each submodel, pad for node size and you're good to go.

**Comment by aekiss** [comment]
Ah OK sorry. Yes, that would be a nice feature :-)

**Comment by aidanheerdegen** [comment]
Sorry, should have been clearer. That is a current feature. The bug is that `payu` does not check that the two values are consistent.

**Comment by aekiss** [comment]
So in this case could we just set the overall ncpus: 5559 and trust payu to pad it appropriately for normal or normalbw?

**Comment by aekiss** [comment]
If so, for coupled runs payu should just ignore the overall ncpus requested in config.yaml. (At present it uses the overall ncpus in the qsub.)

**Comment by aidanheerdegen** [comment]
As I read the code you should be able to NOT set an overall `ncpus` and `payu` will determine the total, and pad as appropriate.

**Comment by aekiss** [comment]
Ah OK so it's best to leave it off then. Thanks, that's handy to know!

**Comment by marshallward** [comment]
I agree it's not too urgent, a warning should probably suffice.  Mostly I just wanted to quote Khadgar.

**Comment by aidanheerdegen** [comment]
It's a cool quote.

**Comment by aekiss** [comment]
It didn't work to comment out the total ncpus request in config.yaml.
I got this error in /projects/v45/apps/payu/aek:
```
Traceback (most recent call last):
  File "/projects/v45/apps/payu/aek/bin/payu", line 8, in <module>
    cli.parse()
  File "/projects/v45/apps/payu/aek/lib/payu/cli.py", line 61, in parse
    run_cmd(**args)
  File "/projects/v45/apps/payu/aek/lib/payu/subcommands/run_cmd.py", line 62, in runcmd
    n_cpus_request += submodel_config[model].get('ncpus', 0)
TypeError: list indices must be integers, not dict
```

**Comment by marshallward** [comment]
This has become slightly more serious, since I did an OM2 run where the ncpus was too small and the model failed silenty and then proceeded to archive non-existent data.

The silent fail is worrying, and should also be solved, but this was also a consequence of nonsense CPU counts.

----

And yes, Andrew, currently `ncpus` is necessary.  The feature that Aidan and I were referring to is that payu will automatically pad ncpus to fill up the node and satisfy PBS.

To eliminate ncpus would take some extra work, which I now consider **_URGENT_**!

**Comment by marshallward** [comment]
In going over the code for the upcoming course, I have noticed that we do actually sum up the cpus for each submodel when `ncpus` is not present.  So in principle, it may be possible to omit `ncpus` when it is set for the submodels.

I need to go and test this out, but this issue may have been solved all along.

**Comment by aekiss** [comment]
With the version of payu in analysis3-20.04 it works to omit the total ncpus and let payu determine it, so I've removed total ncpus  from config.yaml in the new configs

**Comment by aidanheerdegen** [comment]
There are currently no configurations experiencing this issue. Not sure if the code still supports specifying a total number of cpus, but I'll close this until it rears it's head again as a problem.
